# Generated by Django 5.2.1 on 2025-05-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networklink",
            name="debt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Долг перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="networklink",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="network.NetworkProduct",
                to="network.product",
                verbose_name="Товары",
            ),
        ),
    ]
