# Generated by Django 5.2.1 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_networklink_debt_alter_networklink_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networklink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="networklink",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="network.NetworkProduct",
                to="network.product",
                verbose_name="Товары",
            ),
        ),
    ]
