# Generated by Django 5.2.1 on 2025-06-02 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_networklink_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networklink",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
